version: '3'
services:
  mercury-parser:
    image: wangqiru/mercury-parser-api
    ports:
      - "3000:3000"
    restart: always
    environment:
      - PORT=3000

  rsshub:
    image: diygod/rsshub
    ports:
      - "1200:1200"
    restart: always
    environment:
      - NODE_ENV=production
      - CACHE_TYPE=memory
