name: everything_rss
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  chewie: ^1.13.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  just_audio: ^0.10.5
  video_player: ^2.11.1
  http: ^1.2.0
  xml: ^6.3.0
  path_provider: ^2.1.5
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  flutter_riverpod: ^3.3.1
  audio_service: ^0.18.18
  audio_session: ^0.2.3
  simple_pip_mode: ^1.1.0
  cached_network_image: ^3.4.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  hive_ce_generator: ^1.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/media/