// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:everything_rss/features/feeds/data/models/downloaded_media.dart';
import 'package:everything_rss/features/feeds/data/models/local_feed_folder.dart';
import 'package:everything_rss/features/feeds/data/models/local_feed_item.dart';
import 'package:everything_rss/features/feeds/data/models/saved_feed_entry.dart';
import 'package:everything_rss/features/feeds/data/models/third_party_server.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DownloadedMediaAdapter());
    registerAdapter(LocalFeedFolderAdapter());
    registerAdapter(LocalFeedItemAdapter());
    registerAdapter(SavedFeedEntryAdapter());
    registerAdapter(ThirdPartyServerAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DownloadedMediaAdapter());
    registerAdapter(LocalFeedFolderAdapter());
    registerAdapter(LocalFeedItemAdapter());
    registerAdapter(SavedFeedEntryAdapter());
    registerAdapter(ThirdPartyServerAdapter());
  }
}
